# Modified by smalvy, 2026 — adapted for portfolio-project-1
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-project-1

  Sample SAM Template for portfolio-project-1

Parameters:
  AlertEmail:
    Type: String
    Description: E-mail address to receive CloudWatch alerts

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ItemsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ResourcePolicy:
          IpRangeWhitelist:
            - "#IP IN CIDR NOTATION (xxx.xxx.xxx.xxx/xx) TO LIMIT THE ACCESS ON API GATEWAY#"
  ItemsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: items/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Events:
        GetItems:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items
            Method: get
            RestApiId: !Ref ItemsApi
        PostItems:
          Type: Api
          Properties:
            Path: /items
            Method: post
            RestApiId: !Ref ItemsApi
      Tags:
        Project: portfolio-project-1
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
          DYNAMODB_ENDPOINT: "" # Set it to "http://host.docker.internal:4566" to deploy on LocalStack
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      Tags:
        Project: portfolio-project-1
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Project
          Value: portfolio-project-1
  AlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref AlertEmail
      TopicArn: !Ref AlertsTopic
  AlertsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ErrorItemsFunctionAlarm
      AlarmDescription: Alarm raised when the number of errors in the ItemsFunction invocations exceeds the threshold during a period of time
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref ItemsFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !GetAtt AlertsTopic.TopicArn


Outputs:
  ItemsApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Items function"
    Value: !Sub "https://${ItemsApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/items/"
  ItemsFunction:
    Description: "Items Lambda Function ARN"
    Value: !GetAtt ItemsFunction.Arn
  ItemsFunctionIamRole:
    Description: "Implicit IAM Role created for Items function"
    Value: !GetAtt ItemsFunctionRole.Arn
